all:
	g++ -std=c++14 1-main.cpp 2-twoDmain.cpp 3-LineDrawing.cpp 4-InputFor2D.cpp 5-3DviewWindow.cpp 6-threeDmain.cpp 7-LineDrawingFor3Dto2D.cpp 8-InputFor3Dto2D.cpp 9-2DviewWindow.cpp 10-display_main.cpp  -lGL -lglut -lglui -lGLU `pkg-config --cflags --libs gtk+-2.0`




#all:
#	g++ 1-main.cpp 2-twoDmain.cpp 3-LineDrawing.cpp 4-InputFor2D.cpp 5-3DviewWindow.cpp 6-threeDmain.cpp 7-LineDrawingFor3Dto2D.cpp 8-InputFor3Dto2D.cpp 9-2DviewWindow.cpp -lGL -lglut -lglui


#ok:
#1-main.cpp 2-twoDmain.cpp 3-LineDrawing.cpp 4-InputFor2D.cpp 5-3DviewWindow.cpp 6-threeDmain.cpp 7-LineDrawingFor3Dto2D.cpp 8-InputFor3Dto2D.cpp 9-2DviewWindow.cpp
